const IDENTITY_TERMS = [
  'Arnav',
  'Arnav Gupta',
  'Orion',
  'Oracia',
  'Seekho',
  'Ascending Version',
  'Upwork',
  'GitHub',
] as const;

const VOICE_AND_AI_TERMS = [
  'Gemini',
  'Gemini 3.1 Flash-Lite',
  'Deepgram',
  'Nova-3',
  'Flux',
  'Flux General English',
  'Aura-2 Orion',
  'Wispr Flow',
  'Jarvis',
  'Tony Stark',
  'STT',
  'TTS',
  'LLM',
] as const;

const ENGINEERING_TERMS = [
  'Cloudflare',
  'Cloudflare Workers',
  'Workers.dev',
  'Wrangler',
  'MediaPipe',
  'Three.js',
  'LangGraph',
  'WebRTC',
  'WebSocket',
  'JavaScript',
  'TypeScript',
  'Vite',
  'M5 MacBook Air',
] as const;

const CAREER_CONTEXT_TERMS = [
  'VP of Engineering',
  'AI infrastructure',
  'AI agent architect',
  'agentic AI',
  'multimodal',
  'realtime',
  'low latency',
  'Durable Objects',
  'Queues',
  'KV',
  'Vectorize',
  'R2',
  'SFU',
  'RAG',
  'GAIA benchmark',
  'Web Summit Rio',
  'Top Rated Plus',
] as const;

const ORB_TERMS = [
  'orb',
  'orbs',
  'sphere',
  'solar core',
  'inner core',
  'light source',
  'energy core',
  'triangle shell',
  'triangle lattice',
  'skeleton',
  'field',
  'reticle',
  'brightness',
  'energy',
  'yaw',
  'pitch',
  'roll',
] as const;

const GESTURE_TERMS = [
  'pinch',
  'pinch and drag',
  'grab',
  'closed fist',
  'open palm',
  'two palms',
  'two hands',
  'dual control',
  'hand tracking',
  'field open',
  'open the field',
  'expand the field',
  'collapse the field',
  'close the field',
  'retract the field',
  'open the orb',
  'expand the orb',
  'unfold the orb',
  'disperse the orb',
  'charge the orb',
  'burst',
  'blast',
  'release energy',
  'zoom in',
  'zoom inside',
  'zoom out',
  'rotate left',
  'rotate right',
  'tilt up',
  'tilt down',
  'spin',
  'x-axis',
  'y-axis',
  'z-axis',
  'stop motion',
  'increase brightness',
  'decrease brightness',
  'increase core size',
  'decrease core size',
  'increase energy',
  'decrease energy',
  'reset',
  'restore the orb',
] as const;

const PAGE_ACTION_TERMS = [
  'open URL',
  'open GitHub',
  'show content',
  'inspect Orion state',
  'copy text',
  'fullscreen',
  'exit fullscreen',
  'stop speaking',
  'cancel',
] as const;

export const ORION_TRANSCRIPTION_TERMS = [
  ...IDENTITY_TERMS,
  ...VOICE_AND_AI_TERMS,
  ...ENGINEERING_TERMS,
  ...CAREER_CONTEXT_TERMS,
  ...ORB_TERMS,
  ...GESTURE_TERMS,
  ...PAGE_ACTION_TERMS,
] as const;

export function buildGeminiTranscriptionPrompt(): string {
  return [
    'Transcribe the spoken audio exactly.',
    'Preserve every completed word, especially the final words spoken immediately before the recording stops.',
    'Return only the verbatim transcript. Do not answer, explain, summarize, translate, add quotation marks, or add speaker labels.',
    '',
    "The speaker is demonstrating Orion, Arnav Gupta's voice-controlled 3D orb and browser agent.",
    'Contextual vocabulary and canonical spellings:',
    ORION_TRANSCRIPTION_TERMS.join(', '),
    '',
    'Important disambiguation: spell the person\'s name Arnav; the product Orion; the company Oracia; the speech provider Deepgram (not "Deep Ground"); the dictation app Wispr Flow; and the model Gemini 3.1 Flash-Lite when the audio supports those meanings.',
    'These are spelling and context hints only. Never insert, substitute, or force a listed term unless the audio and sentence context support it. Preserve ordinary words such as "flashlight", "ball", or "origin" when that is what was actually spoken.',
  ].join('\n');
}
